{{- if eq .Values.SecretProviderClass.enable true -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "demo.fullname" . }}-secret-provider-class
spec:
  provider: {{ .Values.SecretProviderClass.provider }}
  parameters:
    {{- if eq .Values.SecretProviderClass.provider "azure" }}
    {{- with .Values.SecretProviderClass.parameters }}
    keyvaultName: .keyvaultName
    tenantId: .tenantId
    objects: | {{ nindent 6 .objects }}
    {{- end -}}
    {{ else if eq .Values.SecretProviderClass.provider "aws" }}
    {{ else if eq .Values.SecretProviderClass.provider "gcp" }}
    {{ else if eq .Values.SecretProviderClass.provider "vault" }}
    {{ end }}
  # The new Kubernetes secret to create
  secretObjects:
    # Name of the new Kubernetes secret
    - secretName: foo-secrets
      type: Opaque
      data:
        # A key name inside the new secret
        - key: databasepassword
          # Secret value to use
          objectName: key-vault-secret-1
        - key: clientsecret
          objectName: key-vault-secret-2
{{- end -}}