{{- if .Values.SecretProviderClass.enable -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secrets-microservice-foo
spec:
  provider: {{ .Values.SecretProviderClass.provider }}
  parameters:
    {{- range $k, $v := .Values.SecretProviderClass.parameters  }}
    {{ $k }}: {{ $v }}
    {{- end -}}
  # The new Kubernetes secret to create
  secretObjects:
    # Name of the new Kubernetes secret
    - secretName: foo-secrets
      type: Opaque
      data:
        # A key name inside the new secret
        - key: databasepassword
          # Secret value to use
          objectName: key-vault-secret-1
        - key: clientsecret
          objectName: key-vault-secret-2
{{- end -}}